#! /bin/sh

# This file is provided by copr-frontend.rpm package, but we edit it for the
# purpose of Fedora Copr instance.  Please consult
#     $ dnf diff copr-frontend /etc/cron.hourly/copr-frontend-optional
# to see our changes, and perhaps update when appropriate.

runuser -c '/usr/share/copr/coprs_frontend/run/check_for_anitya_version_updates.py --backend pypi --delta=172800 &> /dev/null' - copr-fe
runuser -c '/usr/share/copr/coprs_frontend/run/check_for_anitya_version_updates.py --backend rubygems --delta=172800 &> /dev/null' - copr-fe
