#!/bin/bash
# Backup a database *locally* to /backups/.

DB=$1

# Make our latest backup
/usr/bin/pg_dump --exclude-table-data=sessions -C $DB | /usr/bin/pxz > /backups/$DB-$(date +%F).dump.xz

# Also, delete the backup from a few days ago.
rm -f /backups/$DB-$(date --date="2 days ago" +%F).dump.xz
