#!/bin/sh

source /root/sshagent >>/dev/null

TMPDIR=`mktemp -d /tmp/backups.XXXX`

cd $TMPDIR
git clone http://infrastructure.fedoraproject.org/infra/ansible.git
ansible-playbook -i ansible/inventory ansible/playbooks/rdiff-backup.yml 
