#!/usr/bin/python
# puppet/modules/datagrepper/templates/fedmsg-hub.erb
__requires__ = ['fedmsg', 'SQLAlchemy >= 0.7', 'jinja2 >= 2.4']
import os
import sys
from pkg_resources import load_entry_point
os.environ['DATAGREPPER_CONFIG'] = '/etc/datagrepper/datagrepper.cfg'

if __name__ == '__main__':
    sys.exit(
        load_entry_point('fedmsg', 'console_scripts', 'fedmsg-hub')()
    )
