#!/bin/bash
set -e
log=/var/log/java-deptools/backend.log
cd /var/lib/java-deptools/repos/
date > $log
java-deptools-repogen f29 f28 f27 f26 &> $log
date > $log
echo 'Repo regeneration successful' >> $log
