#!/bin/bash
# Redirect stdin to each of the post-receive hooks in place.

# You need to explicitly add your hook to the following list
# for it to be invoked.
pee \
    $GIT_DIR/hooks/post-receive-chained.d/post-receive-email \
    $GIT_DIR/hooks/post-receive-chained.d/post-receive-fedmsg
