#!/bin/bash
# Redirect stdin to each of the post-receive hooks in place.

# You need to explicitly add your hook to the following list
# for it to be invoked.
pee \
    $GIT_DIR/hooks/post-receive-chained.d/post-receive-fedmsg
    $GIT_DIR/hooks/post-receive-chained.d/post-receive-alternativearch

# We used to send emails directly from the git hook here, but now we send to
# fedmsg which routes to FMN which routes to packagers and the mailing list.
#$GIT_DIR/hooks/post-receive-chained.d/post-receive-email \
