#!/bin/bash


refname="${1}"
sha1_old="${2}"
sha1_new="${3}"


$GIT_DIR/hooks/update-chained.d/update-gitolite "$refname" "$sha1_old" "$sha1_new" || exit 1
$GIT_DIR/hooks/update-chained.d/update-block-push-origin "$refname" "$sha1_old" "$sha1_new" || exit 1

exit 0
