#!/bin/sh
#
# Block pushes to branches if their name starts with `origin/`
# https://fedorahosted.org/rel-eng/ticket/4071

refname="${1}"
sha1_old="${2}"
sha1_new="${3}"

echo "${refname}" | grep -qE '^refs/heads/origin/' && exit 1 || exit 0
