#! /bin/sh

# This file is provided by copr-frontend.rpm package, but we edit it for the
# purpose of Fedora Copr instance.  Please consult
#     $ dnf diff copr-frontend /etc/cron.daily/copr-frontend-optional
# to see our changes, and perhaps update when appropriate.

runuser -c 'copr-frontend notify_outdated_chroots' - copr-fe
runuser -c 'copr-frontend delete_outdated_chroots' - copr-fe
