#! /bin/sh

# This file is provided by copr-frontend.rpm package, but we edit it for the
# purpose of Fedora Copr instance.  Please consult
#     $ dnf diff copr-frontend /etc/cron.daily/copr-frontend-optional
# to see our changes, and perhaps update when appropriate.

runuser -c 'copr-frontend notify-outdated-chroots' - copr-fe
runuser -c 'copr-frontend delete-outdated-chroots' - copr-fe
/usr/bin/bash /usr/libexec/copr_dump_db.sh /var/www/html/db_dumps/
