#!/bin/sh                                                                                  

/usr/bin/rsync -aSHPv --delete --exclude=.git/objects/ sundries01::docs/ /srv/web/docs.fedoraproject.org/
/usr/bin/rsync -aSHPv --delete --exclude=.git/objects/ sundries01::docs-redirects/ /srv/web/docs-redirects/

# build the combined docs tree. 
# See https://pagure.io/fedora-infrastructure/issue/7130

/usr/bin/rsync -aSHPv --link-dest=/srv/web/docs-old.fedoraproject.org/public_html/ /srv/web/docs-old.fedoraproject.org/public_html/ /srv/web/docs-combined/
/usr/bin/rsync -aSHPv --link-dest=/srv/web/docs-old.fedoraproject.org/public_html //srv/web/docs-redirects/ /srv/web/docs-combined/
/usr/bin/rsync -aSHPv --link-dest=/srv/web/docs-old.fedoraproject.org/public_html/ /srv/web/docs.fedoraproject.org/ /srv/web/docs-combined/
