#!/usr/bin/python
__requires__ = ['fedmsg>=0.13.1', 'WebOb>=0.9.7', 'sqlalchemy>=0.7']
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('fedmsg', 'console_scripts', 'fedmsg-hub')()
    )
