#! /bin/sh

set -e

for name in \
    builder-repositories.repo \
    download \
    prepare-disk \
    promote-disk \
    upload-disk; \
do
    curl https://infrastructure.fedoraproject.org/cgit/ansible.git/plain/roles/copr_hypervisor_aarch64/files/"$name" \
        > "$name"
done
