#! /bin/sh -x

die() { echo >&2 "$*" ; exit 1 ; }

volume_promoted=$1
volume=copr-builder

# the only pool where we can work with qcow2 images (which is effective,
# compared to raw images)
pool=images

new_volume=copr-builder-$(date +"%Y%m%d_%H%M%S")

connections='
    qemu:///system
    qemu+ssh://copr@virthost-aarch64-os02.fedorainfracloud.org/system
'

test -n "$volume" || die "first argument (volume) required"

for connection in $connections; do
    virsh --connect="$connection"  vol-delete "$volume" --pool "$pool"
    virsh --connect="$connection"  vol-clone "$volume_promoted" "$volume" --pool "$pool"
done

echo "copr-builder == $volume_promoted now"
