#!/bin/sh                                                                                  

/usr/bin/rsync -aSHPv --delete --exclude=.git/objects/ sundries01::docs-old/ /srv/web/docs-old.fedoraproject.org/
