#!/bin/bash
dnsgit='https://infrastructure.fedoraproject.org/infra/dns.git'
destdir='/var/named/master/'

if [ -d $destdir ];
then
  cd $destdir
  git pull -X theirs
else
  git clone $dnsgit $destdir
fi
cd $tmpdir

# change context so the chroot can cope
chown -R named.named $destdir
chcon -u system_u $destdir/* $destdir/*/*
# reload named
/sbin/service named reload
