#!/bin/bash
#
# 2014-11-19
# Author: Ralph Bean <rbean@redhat.com>

# exit codes
ok=0
warn=1
crit=2
unkn=3

# Right now we just check to see if we can even run this command without
# hanging and timing out.  In the future, we could parse stdout for more
# fine-grained information.
echo stats | nc 127.0.0.1 11211 > /dev/null
status=$?

if [ $status -ne 0 ]; then
    echo "CRIT:  stats command got status code $status"
    exit $crit
else
    echo "OK:  stats command got status code $status"
    exit $ok
fi
