#!/bin/bash

RUNNING_VMS=`testcloud instance list | grep -i 'running' | wc -l`
CRITICAL=20
WARNING=15


if [ $RUNNING_VMS -gt $CRITICAL ]
then
    echo "Testcloud: CRITICAL Number of VMs running: $RUNNING_VMS"
    exit 2
elif [ $RUNNING_VMS -gt $WARNING ]
then
    echo "Testcloud: WARNING Number of VMs running: $RUNNING_VMS"
    exit 1
else
    echo "Testcloud: OK Number of VMs running: $RUNNING_VMS"
    exit 0
fi
