#!/bin/bash

if [ -z $1 ]; then
   echo "You must specify a planet name" >&2
   exit 1
fi

if [ -f /srv/planet/config/$1/config.ini ]; then
    /usr/local/bin/lock-wrapper "$1" "/usr/bin/venus-planet /srv/planet/config/$1/config.ini"
else
    echo "Cannot find /srv/planet/config/$1/config.ini - Exiting" >&2
    exit 1
fi




