FROM bodhi-base
LABEL \
  name="bodhi-web" \
  vendor="Fedora Infrastructure" \
  license="MIT"
RUN dnf install --refresh -y bodhi-docs-{{bodhi_version}} python3-pyramid_sawing
EXPOSE 8080
ENTRYPOINT bash /etc/bodhi/start.sh
