#!/usr/bin/python2

# NOTE - we hotfix this with ansible so we can do alembic with a forward-compat
# el7 package for webob.  -- threebean

import __main__
__requires__ = __main__.__requires__ = ['WebOb>=1.4.1', 'alembic']
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(load_entry_point('alembic', 'console_scripts', 'alembic')())
