#!/usr/bin/python
# -*- coding: utf-8 -*-

# Software License Agreement (BSD License)
#
# Copyright (c) 2009-2011, Eucalyptus Systems, Inc.
# All rights reserved.
#
# Redistribution and use of this software in source and binary forms, with or
# without modification, are permitted provided that the following conditions
# are met:
#
#   Redistributions of source code must retain the above
#   copyright notice, this list of conditions and the
#   following disclaimer.
#
#   Redistributions in binary form must reproduce the above
#   copyright notice, this list of conditions and the
#   following disclaimer in the documentation and/or other
#   materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Author: Neil Soman neil@eucalyptus.com
#         Mitch Garnaat mgarnaat@eucalyptus.com


# additions below added by seth vidal skvidal@fedoraproject.org

import euca2ools.commands.euca.describeinstances
import euca2ools.commands.euare.listaccounts
import euca2ools.utils
import prettytable
import time
import sys
from operator import itemgetter

if __name__ == '__main__':
    la = euca2ools.commands.euare.listaccounts.ListAccounts()
    accts = {}
    response = la.main()
    for acct in response.Accounts:
        accts[acct['AccountId']] = acct['AccountName']
    
    di = euca2ools.commands.euca.describeinstances.DescribeInstances()
    if len(sys.argv) < 2:
        di.instance=['verbose']
    else:
        di.instance = sys.argv[1:]
    res = di.main()
    fields = ('reservation','id','owner','status','network', 'key', 'type', 'start')
    pt = prettytable.PrettyTable(fields)
    for r in res:
        for i in r.instances:
            if i.state == 'terminated':
                continue
           
            start = time.strftime('%Y-%m-%d %H:%M:%S', time.strptime(i.launch_time.split('.')[0], '%Y-%m-%dT%H:%M:%S'))
            net = '%s' % i.ip_address
            pt.add_row([r.id, i.id, accts[r.owner_id], i.state, net, i.key_name, i.instance_type, start])
    
    pt.printt(sortby='start', reversesort=True)
    
            
        
        
        
        
