#!/bin/bash

#
# A simple script to copy database dumps over to public space on lockbox01
# Only the most recent dump is published
#
scp db-datanommer02:/backups/datanommer-$(date +%F).dump.xz /srv/web/infra/db-dumps/datanommer.dump.xz
scp db-koji01:/backups/koji-$(date +%F).dump.xz /srv/web/infra/db-dumps/koji.dump.xz
scp db01:/backups/pkgdb2-$(date +%F).dump.xz /srv/web/infra/db-dumps/pkgdb2.dump.xz
scp db01:/backups/fedoratagger-$(date +%F).dump.xz /srv/web/infra/db-dumps/fedoratagger.dump.xz
scp anitya-backend01:/backups/anitya-$(date +%F).dump.xz /srv/web/infra/db-dumps/anitya.dump.xz
