#!/bin/bash

#
# A simple script to copy database dumps over to public space on lockbox01
# Only the most recent dump is published
#

scp db-datanommer01:/backups/datanommer-$(date +%F).dump.xz /srv/web/infra/db-dumps/datanommer.dump.xz
