#!/usr/bin/python
# This file is managed by ansible.
#
# Its like "permanent hotfix" so that the fedmsg-hub loads
# the forward-compat sqlalchemy.
#

__requires__ = ['fedmsg', "sqlalchemy>=0.8"]
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('fedmsg', 'console_scripts', 'fedmsg-hub')()
    )

