#!/bin/bash
if [ "$#" -lt 2 ]; then
    echo "Usage: refresh-group <group-name> <repoquery-args>..."
    exit 1
fi
set -e
repodata=`find /var/cache/koschei/repodata/ -path '*/primary-f*' -name repomd.xml | sort -nr | head -n1`
repoid=`grep -o 'primary-[^/]*' <<< "$repodata"`
group=$1
shift
dnf repoquery --repofrompath "$repoid,$repodata" --disablerepo \* --enablerepo "$repoid" --repoid "$repoid" --srpm --qf '%{name}' "$@" | koschei-admin edit-group "$group" --content-from-file - --append
