#!/bin/bash
if [ "$#" -lt 2 ]; then
    echo "Usage: refresh-group <group-name> <repoquery-args>..."
    exit 1
fi
set -e
repodata=`find /var/cache/koschei/repodata/ -maxdepth 1 -type d -name 'primary-f*' | sort -nr | head -n1`
repoid=`basename repodata`
group=$1
shift
dnf repoquery --repofrompath "$repoid,$repodata/x86_64" --repoid "$repoid" --qf '%{sourcerpm}' "$@" | sed 's|-[^-]*-[^-]*$||' | koschei-admin edit-group "$group" --content-from-file - --append
