#!/usr/bin/env python
""" This is a CLI script for getting all the details of a person
"""

import __main__
__main__.__requires__ = __requires__ = ["tahrir-api", "sqlalchemy>=0.7"]
import pkg_resources
pkg_resources.require(__requires__)

import argparse
import json
import os
import sys

from tahrir_api.dbapi import TahrirDatabase

import fedmsg
import fedmsg.config

import fedbadges.utils


def parse_args():
    parser = argparse.ArgumentParser(__doc__)
    parser.add_argument('--person', default=None, help="A person FAS username")
    args = parser.parser_args()
    return args


def initialize():
    fm_config = fedmsg.config.load_config()
    fm_config['cert_prefix'] = 'fedbadges'
    fm_config['name'] = 'relay_inbound'
    fm_config['active'] = True
    fedmsg.init(**fm_config)
    uri = fm_config['badges_global']['database_uri']
    tahrir = TahrirDatabase(
        uri,
        notification_callback=fedbadges.utils.notification_callback,
    )
    return tahrir


def main(tahrir, nickname):
    payload = {}
    person = tahrir.get_person(nickname=nickname)

    if not person:
        print 'No such person %r' % nickname
        sys.exit(1)

    payload = {
        'id': person.id,
        'nickname': nickname,
        'email': person.email,
        'website': person.website,
        'bio': person.bio,
        'created_on': person.created_on,
        'last_login': person.last_login,
        'opt_out': person.opt_out,
        'rank': person.rank,
        'assertions': []
    }

    assertions = tahrir.get_assertions_by_email(person.email)

    if assertions:
        assertion_list = []
        for assertion in assertions:
            assertion_list.append({
                'badge_id': assertion.badge_id,
                'issued_on': assertion.issued_on
            })

        payload['assertions'] = assertion_list

    print json.dumps(payload)


if __name__ == '__main__':
    args = parse_args()
    if not args.person:
        nickname = os.environ['BADGE_USER']
        if nickname is None:
            print "You must specify a person id."
            sys.exit(1)
    else:
        nickname = args.person

    tahrir = initialize()
    main(tahrir, nickname)
